import React from "react";
import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  header: {
    paddingHorizontal: 15,
    paddingVertical: 40,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  header_user_part: {
    flexDirection: "row",
  },
  header_login_button: {
    backgroundColor: "#F40000",
    borderRadius: 20,
    justifyContent: "center",
    padding: 10,
  },
  header_login_button_title: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  header_user_button: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    marginLeft: 10,
  },
  header_user_button_islogin: {
    backgroundColor: "#F40000",
  },
  header_user_button_notification: {
    backgroundColor: "#009639",
    borderWidth: 2,
    borderColor: "#FFFFFF",
    borderRadius: 6,
    width: 12,
    height: 12,
    position: "absolute",
    right: 0,
    top: -3,
  },
  header_user_button_notlogin: {
    backgroundColor: "#1D1E1C",
  },
  footer: {
    justifyContent: "flex-end",
    height: 130,
    backgroundColor: "#FFFFFF",
  },
  footer_icon_box: {
    width: "100%",
    height: 70,
    flexDirection: "row",
    justifyContent: "space-between",
    borderColor: "#ECEEEF",
    borderWidth: 1.5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowRadius: 20,
    elevation: 6,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 6 },
    alignItems: "center",
  },
  footer_icon_center: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    top: -15,
  },
  tags: {
    marginLeft: 15,
    flexGrow: 0,
    marginBottom: 10,
  },
  main: {
    height: height - 130,
    backgroundColor: "#FFFFFF",
  },
  tag_box: {
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 8,
    height: 36,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 5,
  },
  tag_box_image: {
    width: undefined,
    height: "100%",
    aspectRatio: 1,
    alignSelf: "center",
    borderRadius: 5,
    marginRight: 5,
  },
  tag_box_title: {
    color: "#1D1E1C",
    fontSize: 12,
    fontWeight: "400",
    paddingHorizontal: 2,
    paddingVertical: 4,
  },
  tag_box_selected: {
    borderColor: "#F40000",
  },
  tag_box_notselected: {
    borderColor: "#ECEEEF",
  },
  slider: {
    flexGrow: 0,
  },
  dots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
  },
  active_dot: {},
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 3,
  },
  slider_box_wrapper: {
    width: 305,
    height: 383,
    position: "relatives",
    overflow: "hidden",
  },
  slider_box_back: {
    position: "absolute",
    bottom: 7,
    left: 0,
    right: 0,
    top: 15,
    borderRadius: 20,
    transform: [{ skewY: "3deg" }],
  },
  slider_box_front: {
    position: "absolute",
    top: 0,
    bottom: 20,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#F4F6F5",
    zIndex: 100,
  },
  slider_Image_box: {
    flex: 1,
    width: "100%",
    height: "100%",
    position: "relative",
    padding: 5,
    alignItems: "flex-start",
  },
  slider_Image: {
    width: "100%",
    height: "100%",
    resizeMode: "strech",
    borderRadius: 16,
    borderBottomLeftRadius: 100,
  },
  slider_BrandIcon_box: {
    position: "absolute",
    bottom: 0,
    left: 0,
  },
  slider_BrandIcon: {
    width: 55,
    height: 55,
    aspectRatio: 1,
    alignSelf: "center",
  },
  slider_box_info: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "#1D1E1C",
    borderRadius: 27,
  },
  slider_box_info_text: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 14.8,
    letterSpacing: -0.54,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  slider_box_text: {
    height: 110,
    alignItems: "center",
  },
  slider_box_title: {
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: -0.22,
    fontWeight: "700",
    textAlign: "center",
    paddingHorizontal: 30,
    color:"#1D1E1C"
  },
  go_back_button: {
    backgroundColor: "#1D1E1C",
    width: 40,
    height: 40,
    borderRadius: 20,
    position: "absolute",
    left: 15,
    top: 50,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  promotion_detail_container: {
    backgroundColor: "#FFFFFF",
    flex: 1,
  },
  promotion_detail: {
    height: height - 50,
    flex: 1,
  },
  promotion_detail_box: {
    flex: 1,
    position: "relative",
    height: 355,
  },
  promotion_detail_image_box: {
    shadowRadius: 20,
    elevation: 6,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 6 },
  },
  promotion_detail_image_box_image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderBottomLeftRadius: 100,
  },
  promotion_detail_icon_box: {
    width: 40,
    height: 40,
    position: "absolute",
    left: 10,
    bottom: 0,
    flex: 1,
    zIndex: 100,
  },
  promotion_detail_icon_box_image: {
    width: "100%",
    height: "100%",
    flex: 1,
    resizeMode: "contain",
  },
  promotion_detail_info_box: {
    marginHorizontal: 15,
  },
  promotion_detail_info_box_title: {
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 30,
    letterSpacing: 0.2,
    color: "#1D1E1C",
    marginVertical: 15,
  },
  promotion_detail_info_box_description: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 22,
    color: "#1D1E1C",
  },
  promotion_detail_button: {
    backgroundColor: "#F40000",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 28,
    paddingHorizontal: 50,
    marginHorizontal: 50,
    height: 50,
  },
  promotion_detail_button_text: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 16.1,
    textAlign: "center",
    fontWeight: "700",
    paddingVertical: 14,
  },
});

export default styles;
